/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daa;

/**
 *
 * @author H P
 */
public class Limits extends javax.swing.JFrame {

    /**
     * Creates new form Warning
     */
    public Limits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_bubble = new javax.swing.JLabel();
        lbl_line2 = new javax.swing.JLabel();
        lbl_line3 = new javax.swing.JLabel();
        lbl_line4 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        lbl_line6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(57, 73, 171));
        jPanel1.setLayout(null);

        lbl_bubble.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lbl_bubble.setForeground(new java.awt.Color(240, 98, 146));
        lbl_bubble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bubble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daa/ic_error_white_24dp_1x.png"))); // NOI18N
        lbl_bubble.setText("Program Limitations ");
        lbl_bubble.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(lbl_bubble);
        lbl_bubble.setBounds(70, 20, 260, 40);

        lbl_line2.setBackground(new java.awt.Color(57, 73, 171));
        lbl_line2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line2.setText("**   Can provide up to 12 numbers");
        lbl_line2.setOpaque(true);
        jPanel1.add(lbl_line2);
        lbl_line2.setBounds(35, 150, 328, 38);

        lbl_line3.setBackground(new java.awt.Color(57, 73, 171));
        lbl_line3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line3.setText("**   Can do sorting for only integer numbers");
        lbl_line3.setOpaque(true);
        jPanel1.add(lbl_line3);
        lbl_line3.setBounds(35, 70, 328, 38);

        lbl_line4.setBackground(new java.awt.Color(57, 73, 171));
        lbl_line4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line4.setText("**   Can't do sorting with negative numbers");
        lbl_line4.setOpaque(true);
        jPanel1.add(lbl_line4);
        lbl_line4.setBounds(35, 110, 360, 38);

        btn_create.setBackground(new java.awt.Color(237, 73, 128));
        btn_create.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("OK");
        btn_create.setBorder(null);
        btn_create.setBorderPainted(false);
        btn_create.setContentAreaFilled(false);
        btn_create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create.setOpaque(true);
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel1.add(btn_create);
        btn_create.setBounds(140, 270, 110, 28);

        lbl_line6.setBackground(new java.awt.Color(57, 73, 171));
        lbl_line6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line6.setText("**   Can have maximum of 4 digits for each integer");
        lbl_line6.setOpaque(true);
        jPanel1.add(lbl_line6);
        lbl_line6.setBounds(35, 190, 360, 38);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 405, 330);

        setSize(new java.awt.Dimension(404, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btn_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Limits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Limits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Limits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Limits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Limits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bubble;
    private javax.swing.JLabel lbl_line2;
    private javax.swing.JLabel lbl_line3;
    private javax.swing.JLabel lbl_line4;
    private javax.swing.JLabel lbl_line6;
    // End of variables declaration//GEN-END:variables
}
